# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5.1-node-browsers
         environment:
            PGHOST: localhost
            PGUSER: root
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
       - image: circleci/postgres:10.3-alpine-postgis
         environment:
            POSTGRES_USER: root
            POSTGRES_DB: nb_integration_test

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install server dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        
      # Database setup
      - run:
          command: bundle exec rake db:test:migrate
          environment:
            DATABASE_URL: "postgres://localhost:5432/nb_integration_test"

      # run tests!
      # we exclude integration specs as long as we only have one container
      - run:
          name: run server tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      - run:
          name: install client dependencies
          command: |
            npm install -g elm
            npm install -g elm-test
            elm-package install


      - run:
          name: run client tests
          command: |
            elm-test

  deploy:
    docker:
       - image: circleci/ruby:2.5.0-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:  # add key from CircleCI account based on fingerprint
          fingerprints:
            - "32:72:ca:a8:43:5a:d1:1c:f5:9d:01:5c:ad:0a:e9:ee"

      - run:
          name: Run Heroku Setup Script
          command: bash .circleci/setup-heroku.sh

      - run:
          name: Add Heroku to known_hosts
          environment:
            HEROKU_PUBLIC_KEY: "|1|du6yP6VYFOQt2W1/LcEYuaPQhPg=|Db0+enWeW0eh8Fg3R93yFMZ/U/U= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAu8erSx6jh+8ztsfHwkNeFr/SZaSOcvoa8AyMpaerGIPZDB2TKNgNkMSYTLYGDK2ivsqXopo2W7dpQRBIVF80q9mNXy5tbt1WE04gbOBB26Wn2hF4bk3Tu+BNMFbvMjPbkVlC2hcFuQJdH4T2i/dtauyTpJbD/6ExHR9XYVhdhdMs0JsjP/Q5FNoWh2ff9YbZVpDQSTPvusUp4liLjPfa/i0t+2LpNCeWy8Y+V9gUlDWiyYwrfMVI0UwNCZZKHs1Unpc11/4HLitQRtvuk0Ot5qwwBxbmtvCDKZvj1aFBid71/mYdGRPYZMIxq1zgP1acePC1zfTG/lvuQ7d0Pe0kaw=="
          command: echo $HEROKU_PUBLIC_KEY >> ~/.ssh/known_hosts

      - run:
          name: Deploy Master to Heroku
          environment:
            HEROKU_APP_NAME: polar-temple-72955
          command: |  # this command is framework-dependent and may vary
            heroku git:remote --ssh-git -a $HEROKU_APP_NAME
            git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
        #- deploy:  # only deploy when master successfully builds
        #    requires:
        #      - build
        #    filters:
        #      branches:
        #        only: master
